name: Build Custom RustDesk Windows

on:
  workflow_dispatch:   # 手动触发
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        role: [server, client]   # server=被控端, client=主控端

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Vcpkg
        shell: pwsh
        run: |
          git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
          C:\vcpkg\bootstrap-vcpkg.bat

      - name: Set VCPKG_ROOT
        run: echo "VCPKG_ROOT=C:\\vcpkg" >> $env:GITHUB_ENV

      - name: Install Vcpkg dependencies (manifest mode)
        shell: pwsh
        run: C:\vcpkg\vcpkg install

      - name: Setup role.rs
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path custom -Force | Out-Null
          if ("${{ matrix.role }}" -eq "server") {
              'pub const ROLE: &str = "server";' | Out-File -Encoding UTF8 custom/role.rs
          } else {
              'pub const ROLE: &str = "client";' | Out-File -Encoding UTF8 custom/role.rs
          }

      - name: Build release
        run: cargo build --release --locked

      - name: Rename artifact
        shell: pwsh
        run: |
          mkdir output -Force
          if ("${{ matrix.role }}" -eq "server") {
              copy target\release\rustdesk.exe output\rustdesk-server.exe
          } else {
              copy target\release\rustdesk.exe output\rustdesk-client.exe
          }

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-${{ matrix.role }}
          path: output/*.exe
