name: Build Custom RustDesk

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        role: [client, server]   # client = 主控端, server = 被控端

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true

      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            C:\Users\runneradmin\.cargo\registry
            C:\Users\runneradmin\.cargo\git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup role.rs
        run: |
          echo "fn role() -> &'static str { \"${{ matrix.role }}\" }" > custom/role.rs

      - name: Build release
        run: cargo build --release --bin rustdesk

      - name: Rename artifact
        run: |
          mkdir output
          copy target\release\rustdesk.exe output\rustdesk-${{ matrix.role }}.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: rustdesk-${{ matrix.role }}
          path: output/rustdesk-${{ matrix.role }}.exe
