name: Build Custom RustDesk Windows

on:
  workflow_dispatch:   # 手动触发
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        role: [server, client]  # server=被控端, client=主控端

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Vcpkg
        shell: pwsh
        run: |
          git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
          C:\vcpkg\bootstrap-vcpkg.bat

      - name: Set VCPKG_ROOT
        run: echo "VCPKG_ROOT=C:\\vcpkg" >> $env:GITHUB_ENV

      - name: Install Vcpkg dependencies (manifest mode)
        shell: pwsh
        run: C:\vcpkg\vcpkg install

      - name: Setup role.rs and config.rs
        shell: pwsh
        run: |
          # 创建目录
          New-Item -ItemType Directory -Path custom -Force | Out-Null

          # 写入 role.rs
          if ("${{ matrix.role }}" -eq "server") {
              'pub const ROLE: &str = "server";' | Out-File -Encoding UTF8 custom/role.rs
          } else {
              'pub const ROLE: &str = "client";' | Out-File -Encoding UTF8 custom/role.rs
          }

          # 写入 config.rs，自定义默认配置
          @"
pub const LANGUAGE: &str = "auto";  // 中文/英文自动识别

pub const ENABLE_REMOTE_CONFIG: bool = true;
pub const ENABLE_KEYBOARD_MOUSE: bool = true;
pub const ENABLE_CLIPBOARD_SYNC: bool = true;
pub const ENABLE_TERMINAL: bool = true;
pub const ENABLE_REMOTE_REBOOT: bool = true;
pub const ENABLE_TCP_TUNNEL: bool = true;
pub const ENABLE_BLOCK_INPUT: bool = true;
pub const ENABLE_LAN_DISCOVERY: bool = true;
pub const ENABLE_SERVICE: bool = true;
pub const ENABLE_DIRECT_IP: bool = true;

pub const SHOW_LOGIN: bool = false;
pub const ENABLE_AUTO_UPDATE: bool = false;
pub const SHOW_ABOUT: bool = false;

pub const AUTO_START: bool = true;        // server 默认开机自启
pub const HIDE_UI: bool = true;           // server 隐藏前端界面

pub const DEFAULT_PORT: u16 = 9958;
pub const DEFAULT_PASSWORD: &str = "99589958";
"@ | Out-File -Encoding UTF8 custom/config.rs

      - name: Build release
        run: cargo build --release --locked

      - name: Rename artifact
        shell: pwsh
        run: |
          mkdir output -Force
          if ("${{ matrix.role }}" -eq "server") {
              copy target\release\rustdesk.exe output\rustdesk-server.exe
          } else {
              copy target\release\rustdesk.exe output\rustdesk-client.exe
          }

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-${{ matrix.role }}
          path: output/*.exe
