name: Build Custom RustDesk Windows

on:
  workflow_dispatch:
    inputs:
      default_port:
        description: '默认端口'
        required: true
        default: '21115'
      default_password:
        description: '默认密码'
        required: true
        default: '123456'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        role: [server, client]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Vcpkg
        shell: pwsh
        run: |
          git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
          C:\vcpkg\bootstrap-vcpkg.bat

      - name: Install static dependencies via Vcpkg
        shell: pwsh
        run: |
          # 安装 opus、libvpx、libyuv、aom 静态库
          C:\vcpkg\vcpkg install opus:x64-windows-static libvpx:x64-windows-static libyuv:x64-windows-static aom:x64-windows-static --classic
          setx VCPKG_ROOT C:\vcpkg
          setx VCPKG_DEFAULT_TRIPLET x64-windows-static

      - name: Setup role.rs and config.rs
        shell: pwsh
        env:
          ROLE: ${{ matrix.role }}
          DEFAULT_PORT: ${{ github.event.inputs.default_port }}
          DEFAULT_PASSWORD: ${{ github.event.inputs.default_password }}
        run: |
          # 创建 custom 目录
          New-Item -ItemType Directory -Path custom -Force | Out-Null

          # role.rs
          if ($env:ROLE -eq "server") {
            Set-Content -Path custom/role.rs -Value 'pub const ROLE: &str = "server";' -Encoding UTF8
          } else {
            Set-Content -Path custom/role.rs -Value 'pub const ROLE: &str = "client";' -Encoding UTF8
          }

          # config.rs - 逐行写入
          $lines = @(
            'pub const LANGUAGE: &str = "auto";'
            ''
            'pub const ENABLE_REMOTE_CONFIG: bool = true;'
            'pub const ENABLE_KEYBOARD_MOUSE: bool = true;'
            'pub const ENABLE_CLIPBOARD_SYNC: bool = true;'
            'pub const ENABLE_TERMINAL: bool = true;'
            'pub const ENABLE_REMOTE_REBOOT: bool = true;'
            'pub const ENABLE_TCP_TUNNEL: bool = true;'
            'pub const ENABLE_BLOCK_INPUT: bool = true;'
            'pub const ENABLE_LAN_DISCOVERY: bool = true;'
            'pub const ENABLE_SERVICE: bool = true;'
            'pub const ENABLE_DIRECT_IP: bool = true;'
            ''
            'pub const SHOW_LOGIN: bool = false;'
            'pub const ENABLE_AUTO_UPDATE: bool = false;'
            'pub const SHOW_ABOUT: bool = false;'
            ''
            'pub const AUTO_START: bool = true;'
            'pub const HIDE_UI: bool = true;'
            ''
            "pub const DEFAULT_PORT: u16 = $env:DEFAULT_PORT;"
            "pub const DEFAULT_PASSWORD: &str = '$env:DEFAULT_PASSWORD';"
          )
          Set-Content -Path custom/config.rs -Value $lines -Encoding UTF8

      - name: Build release
        shell: pwsh
        run: |
          $env:VCPKG_ROOT="C:\vcpkg"
          $env:VCPKG_DEFAULT_TRIPLET="x64-windows-static"
          cargo build --release --locked

      - name: Rename artifact
        shell: pwsh
        run: |
          # 确保 output 目录存在
          if (-Not (Test-Path output)) {
            New-Item -ItemType Directory -Path output | Out-Null
          }

          # 根据角色重命名生成文件
          if ($env:ROLE -eq "server") {
              Copy-Item -Path target\release\rustdesk.exe -Destination output\rustdesk-server.exe -Force
          } else {
              Copy-Item -Path target\release\rustdesk.exe -Destination output\rustdesk-client.exe -Force
          }

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-${{ matrix.role }}
          path: output/*.exe
